version: "3.4"

services:
  tests:
    build:
      context: .
      target: build
    env_file: dev/moviesbattle.env
    entrypoint: ["/app/gradlew", "build"]

  game:
    build:
      context: .
      target: moviesbattle
    env_file: dev/moviesbattle.env
    container_name: moviesbattle
    expose:
      - "8080"
    ports:
      - "8080:8080"
