openapi: 3.0.1

info:
  title: Movies Battle API
  description: Endpoints to fun
  version: 0.0.1

servers:
  - url: http://localhost:8080/movie-battle/

tags:
  - name: Game
    description: APIs available to play the game

paths:
  /game/start:
    $include: paths/post-start.yaml
  /game/:id/round:
    $include: paths/get-round.yaml
  /game/:id/bet:
    $include: paths/bet-movie.yaml

components:
  schemas:
    $include: definitions/generic-errors.yaml
    $include: definitions/start.yaml
    $include: definitions/round.yaml
    $include: definitions/bet.yaml

